version: "3.4"
services:
  spark-master:
    image: spark_py:247
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"
  spark-worker:
    image: spark_py:247
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    command: "/start-worker.sh"
    
  spark-livy:
    image: livy-spark:latest
    depends_on:
      - spark-master
    ports:
      - "8998:8998"
    networks:
      - spark-network
    volumes:
      - .:/opt/nifi/nifi-current/external/spark
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
    
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default

